# Generated by Django 5.0.6 on 2024-07-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=5),
        ),
    ]
