# Generated by Django 5.0.6 on 2024-12-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayPlan',
        ),
    ]
