# Generated by Django 5.0.6 on 2024-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuscycle',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
