# Generated by Django 5.0.6 on 2024-08-21 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focussession',
            name='current_cycle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_cycle', to='realtime_timer.focuscycle'),
        ),
    ]
