# Generated by Django 5.0.6 on 2024-08-07 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focuscycle',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)]),
        ),
    ]
