# Generated by Django 5.0.6 on 2024-08-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0002_alter_focussession_current_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focuscycle',
            name='duration',
            field=models.DurationField(help_text='Duration in minutes'),
        ),
    ]
