# Generated by Django 5.0.6 on 2024-08-21 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0003_alter_focuscycle_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focuscycle',
            name='duration',
            field=models.DurationField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2500)]),
        ),
    ]
