# Generated by Django 5.0.6 on 2024-10-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0001_squashed_0004_remove_focuscycle_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focussession',
            name='technique',
            field=models.CharField(choices=[('Camel', 'Camel'), ('Pomodoro', 'Pomodoro'), ('52/17 Method', '52/17 Method'), ('90-Minute Focus Sessions', '90-Minute Focus Sessions'), ('2-Hour Focus Blocks', '2-Hour Focus Blocks'), ('Flowtime Technique', 'Flowtime Technique'), ('Custom Technique', 'Custom Technique')], default='Pomodoro', max_length=30),
        ),
    ]
