# Generated by Django 5.0.6 on 2024-10-16 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0005_alter_focussession_technique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='focussession',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='realtime_timer.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tasks', to='realtime_timer.focussession'),
        ),
    ]
