# Generated by Django 5.0.6 on 2024-08-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0005_alter_focuscycle_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focussession',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='focussession',
            name='timer_state',
            field=models.CharField(choices=[('running', 'running'), ('paused', 'paused'), ('completed', 'completed')], default='running', max_length=9),
        ),
    ]
