# Generated by Django 5.0.6 on 2024-08-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0006_remove_focussession_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuscycle',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
