# Generated by Django 5.0.6 on 2024-10-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0006_alter_task_options_focussession_tasks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focussessionfollower',
            options={'ordering': ['joined_at']},
        ),
    ]
