# Generated by Django 5.0.6 on 2024-10-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0007_alter_focussessionfollower_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='participant_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
