# Generated by Django 5.0.6 on 2024-08-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0007_focuscycle_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionfollower',
            options={'ordering': ['-joined_at']},
        ),
    ]
