# Generated by Django 5.0.6 on 2024-10-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0008_focussession_participant_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='session',
        ),
    ]
