# Generated by Django 5.0.6 on 2024-08-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0008_alter_sessionfollower_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focussession',
            name='total_time_to_focus',
        ),
    ]
