# Generated by Django 5.0.6 on 2024-10-16 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0009_remove_task_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusperiod',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='focus_periods', to=settings.AUTH_USER_MODEL),
        ),
    ]
