# Generated by Django 5.0.6 on 2024-09-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0009_remove_focussession_total_time_to_focus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focussession',
            options={'ordering': ['-created_at']},
        ),
    ]
