# Generated by Django 5.0.6 on 2024-10-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0010_focusperiod_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focussession',
            name='tasks',
        ),
    ]
