# Generated by Django 5.0.6 on 2024-09-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0010_alter_focussession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='followers',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='SessionFollower',
        ),
    ]
