# Generated by Django 5.0.6 on 2024-10-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0011_remove_focussession_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focussession',
            name='timer_started_at',
        ),
    ]
