# Generated by Django 5.0.6 on 2024-09-20 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0011_focussession_followers_delete_sessionfollower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focussession',
            name='followers',
        ),
        migrations.CreateModel(
            name='FocusSessionFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type', models.CharField(choices=[('guest', 'Guest'), ('authenticated', 'Authenticated')], max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='realtime_timer.focussession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'username')},
            },
        ),
    ]
