# Generated by Django 5.0.6 on 2024-09-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0012_remove_focussession_followers_focussessionfollower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focussessionfollower',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
