# Generated by Django 5.0.6 on 2024-09-20 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0013_alter_focussessionfollower_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focussessionfollower',
            name='is_active',
        ),
    ]
