# Generated by Django 5.0.6 on 2024-12-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0013_task_finished_at_user_long_term_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
