# Generated by Django 5.0.6 on 2024-09-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0014_remove_focussessionfollower_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='focussessionfollower',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='focussessionfollower',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='focussessionfollower',
            unique_together={('session', 'username', 'channel_name')},
        ),
    ]
