# Generated by Django 5.0.6 on 2025-04-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0015_task_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='long_term_goals',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_term_goals',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
