# Generated by Django 5.0.6 on 2024-09-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_timer', '0015_alter_focussessionfollower_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='focussessionfollower',
            unique_together={('session', 'username')},
        ),
        migrations.RemoveField(
            model_name='focussessionfollower',
            name='channel_name',
        ),
    ]
