[program:django_app]
# TODO: increase the number of workers before final deployment
command=/home/saurav/focus-timer/venv/bin/uvicorn src.asgi:application --workers 4
directory=/home/saurav/focus-timer/
user=saurav
autostart=true
autorestart=true
redirect_stderr=true

[program:redis_scheduler]
command=/home/saurav/focus-timer/venv/bin/python /home/saurav/focus-timer/apps/realtime_timer/management/commands/redis_scheduler.py
directory=/home/saurav/focus-timer/
user=saurav
autostart=true
autorestart=true
redirect_stderr=true
